### PR TITLE
Support for adding languages and setting their translations

### PR DESCRIPTION
**Pull request by apeisa**
Adds two new methods:

addNewLanguage(string $languageName, string $languageTitle = null) 
setTranslationsToLanguage(string $urlToTranslationsZip, string $languageName = "default")

### CODE REVIEW

**Comment by BernhardBaumrock** [comment]
Thx @apeisa but that does not work:
img

Any ideas? Tried with the new dev and blank profile as superuser...

**Comment by apeisa** [comment]
That is strange, works for me.

What line that 1714 is in your repo? 

I might have some changes, can you compare these:


```
  /**
   * Adds new language if it doesn't exists yet. Also installs language support if missing
   * 
   * @param string $languageName of new language
   * @param string $languageTitle (optional)
   * 
   * @return Language $newLang that was created
   */
  public function addNewLanguage(string $languageName, string $languageTitle = null)
  {
    // Make sure Language Support is installed
    $this->modules->get('LanguageSupport');
    $newLang = $this->languages->get($languageName);
    if (!$newLang->id) {
      $newLang = $this->languages->add($languageName);
      $this->languages->reloadLanguages();
    }
    if ($languageTitle) {
      $newLang->title = $languageTitle;
      $newLang->save('title');
    }
    return $newLang;
  }

  /**
   * Set core translations from zip file to a language. Removes old translations if any.
   * 
   * <code>
   * $rm->addTranslationsToLanguage("https://github.com/apeisa/Finnish-ProcessWire/archive/master.zip", "finnish");
   * </code> 
   * 
   * @param string $urlToTranslationsZip public url to zip file containing translation json files
   * @param string $languageName that is updated
   * 
   * @return Language $language
   */
  public function setTranslationsToLanguage(string $urlToTranslationsZip, string $languageName = "default")
  {
    // Make sure Language Support is installed
    $this->modules->get('LanguageSupport');
    $language = $this->languages->get($languageName);
    if (!$language->id) throw new WireException("Language does not exists.");
    $http = new WireHttp();
    // Download zip to cache folder for unzipping
    $zipTemp = $this->config->paths->cache . $languageName . "_temp.zip";
    $http->download($urlToTranslationsZip, $zipTemp);

    // Unzip files and add .json files to language
    $items = $this->files->unzip($zipTemp, $this->config->paths->cache);
    if (count($items)) {
      // Delete all old files first
      $language->language_files->deleteAll();
      $language->save();
      foreach ($items as $item) {
        if (strpos($item, ".json") === false) continue;
        $language->language_files->add(config()->paths->cache . $item);
      }
    }
    $language->save();

    return $language;
  }

  /**
   * Deletes a language
   * 
   * @param string $languageName
   * 
   * @return void
   */
  public function deleteLanguage(string $languageName)
  {
    if ($languageName == "default") throw new WireException("You cannot delete default language."); // Not sure if this should be allowed?

    $language = $this->languages->get($languageName);
    if (!$language->name) return;

    $this->languages->delete($language);
  }
```

**Comment by BernhardBaumrock** [comment]
This line is throwing the error:
https://github.com/BernhardBaumrock/RockMigrations/pull/5/commits/6a6da768ffc7b70854a86e50b6ca4890020514e0#diff-e75e9472f21ca56b094e176c256ae607R1714

The problem is that the LanguageSupport module is not installed and seems not to be installable via API:

image

image

Ok, interesting... I tried to install LanguageSupport manually and got this:

image

Did some more testing...

Blank profile, only Tracydebugger + RockMigrations installed. Installing LanguageSupport on a fresh copy manually works. Installing it via API does not work properly. I get new db tables:

image

image

But the module is not installed! The processmodule does show some weird entries for setup > languages:

image

Can you reproduce this? Any ideas what could be the problem?

**Comment by BernhardBaumrock** [comment]
Any news @apeisa ?

**Comment by apeisa** [comment]
Sorry about the delay. Just tested this on clean blank install and everything went fine. I do have this on my migration file before running $rm->migrate(<configarray>):

```
modules('LanguageSupport');
$rm->setTranslationsToLanguage("https://github.com/apeisa/Finnish-ProcessWire/archive/master.zip");
modules()->refresh();
```

With those I do get LanguageSupport installed and default language populated with Finnish translations.

**Comment by BernhardBaumrock** [comment]
thx @apeisa I've just added your methods to the latest version of RockMigrations (v0.0.70)

**Pull request closed without merging**
